export function AdminCmsStyles() {
  return (
    <style>{`
      .admin-cms-shell{min-height:100vh;display:grid;grid-template-columns:260px 1fr;background:#061226;color:#fff}
      .admin-cms-sidebar{padding:28px;background:#020814;border-right:1px solid rgba(255,255,255,.1);position:sticky;top:0;height:100vh}
      .admin-cms-sidebar strong{display:block;font-size:1.05rem;margin-bottom:24px}.admin-cms-sidebar nav{display:grid;gap:8px}.admin-cms-sidebar a{color:#d9e8ff;text-decoration:none;padding:12px 14px;border-radius:12px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.06)}.admin-cms-sidebar a:hover{background:rgba(13,110,253,.2)}
      .admin-cms-main{padding:30px;min-width:0}.admin-cms-header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:24px}.admin-cms-header h1{margin:0;font-size:clamp(2rem,4vw,3.4rem);letter-spacing:-.04em}.admin-cms-header p{margin:8px 0 0;color:#b7cdec}.admin-cms-view-site,.admin-cms-button{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 16px;border-radius:12px;background:#0d6efd;color:#fff;text-decoration:none;border:0;font-weight:800;cursor:pointer}.admin-cms-button.secondary{background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.14)}.admin-cms-button.danger{background:#dc3545}
      .admin-cms-card{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);border-radius:22px;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.22)}.admin-cms-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.admin-cms-form{display:grid;gap:14px;margin-bottom:24px}.admin-cms-form.two{grid-template-columns:1fr 1fr}.admin-cms-form label{display:grid;gap:7px;color:#dcecff;font-weight:700}.admin-cms-form input,.admin-cms-form textarea,.admin-cms-form select{width:100%;border:1px solid rgba(255,255,255,.14);border-radius:12px;background:#020814;color:#fff;padding:12px;font:inherit}.admin-cms-form textarea{min-height:110px;resize:vertical}.admin-cms-table{width:100%;border-collapse:collapse;overflow:hidden}.admin-cms-table th,.admin-cms-table td{padding:14px;border-bottom:1px solid rgba(255,255,255,.1);text-align:left;vertical-align:top}.admin-cms-table th{color:#8db9ff;font-size:.8rem;text-transform:uppercase;letter-spacing:.08em}.admin-cms-thumb{width:86px;height:64px;object-fit:cover;border-radius:10px;background:#0b1830}.admin-cms-actions{display:flex;gap:8px;flex-wrap:wrap}.admin-cms-status{display:inline-flex;padding:5px 9px;border-radius:999px;background:rgba(13,110,253,.18);color:#8db9ff;font-weight:800;font-size:.78rem}.admin-cms-error{background:#351118;color:#ffb3bd;border:1px solid #812230;padding:12px;border-radius:12px}.admin-cms-success{background:#102b19;color:#b9ffd0;border:1px solid #246a3a;padding:12px;border-radius:12px}
      @media(max-width:900px){.admin-cms-shell{grid-template-columns:1fr}.admin-cms-sidebar{position:relative;height:auto}.admin-cms-sidebar nav{grid-template-columns:repeat(2,1fr)}.admin-cms-main{padding:18px}.admin-cms-grid,.admin-cms-form.two{grid-template-columns:1fr}.admin-cms-header{display:block}.admin-cms-table{font-size:.9rem}}
    `}</style>
  );
}
